version: "3.9"

services:
    api:
        container_name: api
        build: .
        ports:
            - 3000:3000
        environment:
            - DB_HOST=db
            - DB_PASSWORD=1234
            - DB=donus_db
            - DB_USER=ordinary_name
            - SECRET_KEY=Aloha
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/app

    db:
        container_name: db
        image: postgres:14
        ports:
            - 5431:5432
        environment:
            - POSTGRES_USER=ordinary_name
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=donus_db
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ordinary_name -d donus_db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s
